<a href="https://colab.research.google.com/github/Vankum100/colabs/blob/dl-requirements/Numpy_Tutorial.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Arrays vs Lists


In [1]:
import numpy as np


In [2]:
L = [1,2,3]

In [3]:
A = np.array([1,2,3])

In [4]:
for e in L :
  print(e)

1
2
3


In [5]:
for e in A :
  print(e)

1
2
3


In [6]:
L.append(4)
L+ [5]

[1, 2, 3, 4, 5]

In [7]:
A + np.array([4])  #  each element in A is increased by 4

array([5, 6, 7])

In [8]:
A + np.array([1,2,3]) # each element in A is increased by 1 , 2 , 3 respectively

array([2, 4, 6])

In [10]:
#A + np.array([1,2]) # cannot add vectors of different dimensions 

In [13]:
A * 2  

array([2, 4, 6])

In [14]:
L * 2

[1, 2, 3, 4, 1, 2, 3, 4]

In [15]:
L2 = [ e + 3 for e in L] # list comprehension
L2 

[4, 5, 6, 7]

In [19]:
A**2 

array([1, 4, 9])

In [20]:
np.sqrt(A) 

array([1.        , 1.41421356, 1.73205081])

In [21]:
np.log(A)

array([0.        , 0.69314718, 1.09861229])

In [22]:
np.exp(A)

array([ 2.71828183,  7.3890561 , 20.08553692])

In [23]:
np.tanh(A)

array([0.76159416, 0.96402758, 0.99505475])

# Generating Data

In [70]:
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [71]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [72]:
10 * np.ones((2,3))

array([[10., 10., 10.],
       [10., 10., 10.]])

In [73]:
np.eye(2)

array([[1., 0.],
       [0., 1.]])

In [74]:
np.random.random()

0.8405490645958047

In [75]:
np.random.random((2,3))

array([[0.95306159, 0.18794687, 0.68787799],
       [0.30898482, 0.44297841, 0.64394665]])

In [76]:
np.random.randn(2,3)

array([[ 0.82622838,  0.29387232, -1.86497166],
       [-0.31783042,  0.22502615, -0.48047855]])

In [77]:
R = np.random.randn(10000)

In [78]:
R.mean()

-0.0071812779700546866

In [79]:
np.mean(R)

-0.0071812779700546866

In [80]:
R.var() # variance of R 

0.9945336068400272

In [81]:
R.std() # standard deviation of R  = sqrt( R.var())

0.9972630579942422

In [82]:
np.sqrt(R.var())

0.9972630579942422

In [83]:
Rm = np.random.randn(10000, 3) 

In [84]:
Rm.mean( axis= 0) # mean of each column

array([-0.00571081, -0.00368712, -0.00752599])

In [85]:
Rm.mean(axis = 1).shape  # number of rows

(10000,)

In [87]:
np.cov(Rm).shape 

(10000, 10000)

In [89]:
np.cov(Rm.T) # Estimate a covariance matrix, given data and weights.

array([[1.01285965, 0.00959276, 0.01997035],
       [0.00959276, 0.99064573, 0.00714254],
       [0.01997035, 0.00714254, 0.99494366]])

In [91]:
np.cov(Rm, rowvar= False ) # same result without transpose 

array([[1.01285965, 0.00959276, 0.01997035],
       [0.00959276, 0.99064573, 0.00714254],
       [0.01997035, 0.00714254, 0.99494366]])

In [92]:
np.random.randint(0, 10, size = (4, 4)) 

array([[7, 2, 3, 2],
       [2, 6, 4, 6],
       [5, 2, 3, 6],
       [8, 0, 4, 3]])

In [94]:
np.random.choice(10, size =( 3, 3))

array([[8, 4, 6],
       [8, 4, 2],
       [8, 5, 5]])

# The Dot Product

In [24]:
a = np.array([1,2])
b = np.array([3,4])


In [25]:
dot = 0

for e , f in zip(a,b) : 
  dot += e * f 
dot   

11

In [27]:
dot = 0 
for i in range(len(a)) : 
  dot += a[i] * b[i]
dot   

11

In [29]:
np.sum(a * b) # dot product fast method

11

In [30]:
(a * b).sum()

11

In [31]:
np.dot(a,b)  # best practice

11

In [32]:
a.dot(b)

11

In [33]:
a @ b # new way 

11

In [34]:
amag = np.sqrt((a * a).sum())  # magnitude of a = square root of a^2
amag

2.23606797749979

In [35]:
amag = np.linalg.norm(a) # linear algebra normal of a
amag 

2.23606797749979

In [36]:
cos_angle = a.dot(b) / ( np.linalg.norm(a) * np.linalg.norm(b))

cos_angle 

0.9838699100999074

In [37]:
angle_ab = np.arccos(cos_angle)

angle_ab 

0.17985349979247847

In [38]:
list_M = [[1,2], [3,4]]
list_M 

[[1, 2], [3, 4]]

# Matrix

In [39]:
array_M = np.array(list_M)
array_M 

array([[1, 2],
       [3, 4]])

In [41]:
array_M[0][1]

2

In [42]:
array_M[0,1]

2

In [43]:
array_M[:, 0]  # select a column aka every row in that dimension

array([1, 3])

In [44]:
array_M.T  # transpose of matrix 

array([[1, 3],
       [2, 4]])

In [45]:
np.exp(array_M)

array([[ 2.71828183,  7.3890561 ],
       [20.08553692, 54.59815003]])

In [46]:
A = array_M
A 

array([[1, 2],
       [3, 4]])

In [48]:
B = np.array([[1,2,3], [4,5,6]])
B 

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
A.dot(B) # matrix multiplication of A * B = A.B

array([[ 9, 12, 15],
       [19, 26, 33]])

In [51]:
#A.dot(B.T) # ValueError: shapes (2,2) and (3,2) not aligned: 2 (dim 1) != 3 (dim 0)

In [52]:
np.linalg.det(A) 

-2.0000000000000004

In [54]:
np.linalg.inv(A) 

array([[-2. ,  1. ],
       [ 1.5, -0.5]])

In [55]:
np.linalg.inv(A).dot(A)  #  I = A.A^-1


array([[1.00000000e+00, 0.00000000e+00],
       [1.11022302e-16, 1.00000000e+00]])

In [56]:
np.trace(A) # sum of elements of the main diagonal of A 

5

In [57]:
np.diag(A) 

array([1, 4])

In [59]:
np.diag(A).sum() # same as np.trace(A)

5

In [60]:
np.linalg.eig(A) # returns eigen values and eigin vector of A  

(array([-0.37228132,  5.37228132]), array([[-0.82456484, -0.41597356],
        [ 0.56576746, -0.90937671]]))

In [61]:
e_values, e_vector = np.linalg.eig(A) 

e_vector[:,0] * e_values[0] , A @ e_vector[:,0]

(array([ 0.30697009, -0.21062466]), array([ 0.30697009, -0.21062466]))

In [62]:
np.allclose(e_vector[:,0] * e_values[0] , A @ e_vector[:,0])

True

In [64]:
np.allclose(e_vector.dot(np.diag(e_values)),  A.dot(e_vector)) # eigen_vector * eigen_values === matrix * eigen_vector

True

**Solving Linear Equations**


In [65]:
A = np.array([ [1,1], [1.5, 4]]) #  x1 +  x2  = 2200
b = np.array([2200, 5050])     # 1.5x1 + 4x2  = 5050


In [66]:
np.linalg.solve(A,b) # best practice 

array([1500.,  700.])

In [67]:
np.linalg.inv(A).dot(b) # true maths way but not recommended 

array([1500.,  700.])